package cache.logging;

/**
 * A builder for {@link LogEntry}. In order to provide standardized LogEntries,
 * builders can be written.
 * 
 * @author Ben Kimmel
 *
 */
public interface ILogEntryBuilder {

	/**
	 * Returns the {@link LogEntry} generated by the builder.
	 * 
	 * @return The LogEntry generated by the builder
	 */
	public LogEntry build();

	/**
	 * Adds a field to the {@link LogEntry}.
	 * 
	 * @param field
	 *            The name of the field to add
	 * @param value
	 *            The value of the field to add
	 * @return A ILogEntryBuilder that reflects the changes made by this method
	 */
	public ILogEntryBuilder addField(String field, Object value);

}
