package cache.logging.writers;

import java.io.File;
import java.util.List;

import cache.ICacheWrapper;
import cache.logging.LogEntry;
import cache.logging.preprocess.ILogPreprocessor;

/**
 * Processes and writes out the {@link LogEntry} generated by using a
 * {@link ICacheWrapper}.
 * 
 * @author Ben Kimmel
 *
 */
public interface ILogWriter {

	/**
	 * Tells the ILogWriter where to write the output of its processing.
	 * 
	 * @param outputFile
	 *            The File specifying where the output should be written
	 */
	public void setOutputFile(File outputFile);

	/**
	 * Processes and writes an output the the {@link File} specified in
	 * {@link #setOutputFile(File)}.
	 * 
	 * @param logLines
	 *            The list of {@link LogEntry} that is to be processed
	 */
	public void writeLog(List<LogEntry> logLines);
	
	/**
	 * Sets the log preprocessor to be called before logs are handed to the
	 * {@link #writeLog(List)}. This method is optional.
	 * 
	 * @param writer
	 *            The writer with which to produce log files.
	 */
	public void provideLogPreprocessor(ILogPreprocessor preprocessor);

}
