package cache.logging.writers;

import java.io.File;
import java.util.List;

import cache.ICacheWrapper;
import cache.logging.LogEntry;
import cache.logging.preprocess.ILogPreprocessor;

/**
 * Processes and writes out the {@link LogEntry} generated by using a
 * {@link ICacheWrapper}.
 * 
 * @author Ben Kimmel
 *
 */
public interface ILogWriter {

	/**
	 * Tells the ILogWriter the name of the file to write out.
	 * 
	 * @param filename
	 *            The name of the output file
	 */
	public void setOutputFilename(String filename);

	/**
	 * Tells the ILogWriter where to write the output of its processing.
	 * 
	 * @param outputDirectory
	 *            The File specifying where the output should be written
	 */
	public void setOutputDirectory(File outputDirectory);

	/**
	 * Processes and writes an output the the {@link File} specified in
	 * {@link #setOutputDirectory(File)}.
	 * 
	 * @param logLines
	 *            The list of {@link LogEntry} that is to be processed
	 */
	public void writeLog(List<LogEntry> logLines);

	/**
	 * Sets the log preprocessor to be called before logs are handed to the
	 * {@link #writeLog(List)}. This method is optional.
	 * 
	 * @param writer
	 *            The writer with which to produce log files.
	 */
	public void provideLogPreprocessor(ILogPreprocessor preprocessor);

	/**
	 * Returns the name of the log writer.
	 * 
	 * @return The name of the log writer
	 */
	public String getName();

}
